version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    container_name: web
    volumes:
      - ./index.php:/usr/share/nginx/html/index.php
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - dev

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - dev

networks:
  dev:
    driver: bridge
